# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        miniature:
            quality: 75
            filters:
                thumbnail:
                    size: [300, 300]
                    mode: outbound
        welcome:
            quality: 75
            filters:
                scale:
                    dim: [1200, 1200]
        grandeTaille:
            quality: 85
            filters:
                scale:
                    dim: [800, 800]
        portfolio:
            quality: 75
            filters:
                scale:
                    dim: [400, 400]