vich_uploader:
    db_driver: orm

    mappings:
        patisserie_images:
            uri_prefix: '%patisserie_images%'
            upload_destination: '%kernel.project_dir%/public%patisserie_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
